apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: nara1983/jenkinsdockerimage:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8181
        env:
          - name: PORT
            value: "8181"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-whale-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8181
  selector:
    app: hello-whale-app
